services:
  main:
    build:
      target: main
    ports:
      - 8000:8000
    volumes:
      - data:/var/lib/renova
    develop:
      watch:
        - action: sync
          path: ./src
          target: /usr/local/src/renova/src
          ignore: 
            - __pycache__/
        - action: rebuild
          path: ./src/renova/main/templates
        - action: rebuild
          path: ./src/renova/main/styles.css
        - action: rebuild
          path: ./tailwind.config.js
        - action: rebuild
          path: ./compose.yml
        - action: rebuild
          path: ./Dockerfile
        - action: rebuild
          path: ./pyproject.toml
    env_file:
      - .env
volumes:
  data:
