version: '3.9'
services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - data:/var/lib/renova
    develop:
      watch:
        - action: sync
          path: ./src
          target: /usr/local/src/renova/src
          ignore: 
            - __pycache__/
        - action: rebuild
          path: ./pyproject.toml
    env_file:
      - .env

volumes:
  data:
